dbGetQuery(con,

paste("
CREATE TABLE P501B(
    UC CHARACTER(820));

COPY  P501B
FROM 'C:/Users/Public/Documents/DESEMPLEO/",PERFIL.500,"';

DELETE FROM P501B
WHERE UC LIKE '%SEC.RAM.NUM%';

SELECT
CAST(SUBSTRING(UC FROM 1	FOR 3) 		AS  INT) 	AS SEC,--
CAST(SUBSTRING(UC FROM 4	FOR 4) 		AS  INT)	AS RAM,--
CAST(SUBSTRING(UC FROM 8	FOR 14)		AS  BIGINT)	AS NUMERO_POLIZA,	
CAST(SUBSTRING(UC FROM 22	FOR 7)		AS  INT)	AS ENDOSO,--
CAST(SUBSTRING(UC FROM 29	FOR 9)		AS  TEXT)	AS TIPO_END,	
CAST(SUBSTRING(UC FROM 38	FOR 16)		AS  BIGINT)	AS NIT_TOMADOR,	
CAST(SUBSTRING(UC FROM 55	FOR 41)		AS  TEXT)	AS NOMBRE_TOMADOR,	
CAST(SUBSTRING(UC FROM 96	FOR 16)		AS  BIGINT)	AS NIT_ASEGURADO,	
CAST(SUBSTRING(UC FROM 112	FOR 42)		AS  TEXT)	AS NOMBRE_ASEGURADO,
CAST(SUBSTRING(UC FROM 154	FOR 7)		AS  INT)	AS RIESGO,--	
CAST(SUBSTRING(UC FROM 161	FOR 6)		AS  INT)	AS BLOQ,--
CAST(SUBSTRING(UC FROM 167	FOR 13)		AS  TEXT)	AS C_ARTICULO,--	
CAST(SUBSTRING(UC FROM 180	FOR 20)		AS  INT)	AS LOCALIDAD_RIES,--	
CAST(SUBSTRING(UC FROM 200	FOR 40)		AS  TEXT)	AS DIRECCION_RIESGO,	
CAST(SUBSTRING(UC FROM 240	FOR 17)		AS  TEXT)	AS CLAVE_INTERM	,
CAST(SUBSTRING(UC FROM 257	FOR 17)		AS  NUMERIC)	AS COMISION_INTERMD,	
CAST(SUBSTRING(UC FROM 274	FOR 12)		AS  DATE)	AS FEC_VIG_END	,
CAST(SUBSTRING(UC FROM 286	FOR 12)		AS  DATE)	AS FEC_VENC_EN	,
CAST(SUBSTRING(UC FROM 298	FOR 12)		AS  DATE)	AS FEC_VIG_POL	,
CAST(SUBSTRING(UC FROM 310	FOR 12)		AS  DATE)	AS FEC_VENC_PO	,
CAST(SUBSTRING(UC FROM 322	FOR 14)		AS  DATE)	AS FECHA_EMISION,	
CAST(SUBSTRING(UC FROM 336	FOR 13)		AS  DATE)	AS FECHA_EQUIPO	,
CAST(SUBSTRING(UC FROM 349	FOR 5)		AS  INT)	AS MON,	
CAST(SUBSTRING(UC FROM 354	FOR 13)		AS  NUMERIC)	AS TASA_CAMBIO,	
CAST(SUBSTRING(UC FROM 367	FOR 16)		AS  NUMERIC)	AS VALOR_ASEGURADO,
CAST(SUBSTRING(UC FROM 383	FOR 17)		AS  NUMERIC)	AS PRIMA_SEGURO,
CAST(SUBSTRING(UC FROM 400	FOR 5)		AS  NUMERIC)	AS SREA	,
CAST(SUBSTRING(UC FROM 405	FOR 5)		AS  NUMERIC)	AS AGRU	,
CAST(SUBSTRING(UC FROM 410	FOR 16)		AS  NUMERIC)	AS VALOR_RETENIDO,	
CAST(SUBSTRING(UC FROM 426	FOR 17)		AS  NUMERIC)	AS PRIMA_RETENIDA,	
CAST(SUBSTRING(UC FROM 443	FOR 17)		AS  NUMERIC)	AS VALOR_CEDI_CUOTA,	
CAST(SUBSTRING(UC FROM 460	FOR 17)		AS  NUMERIC)	AS PRIMA_CEDI_CUOTA,	
CAST(SUBSTRING(UC FROM 477	FOR 17)		AS  NUMERIC)	AS VALOR_CEDI_EXCED,	
CAST(SUBSTRING(UC FROM 494	FOR 17)		AS  NUMERIC)	AS PRIMA_CEDI_EXCED,	
CAST(SUBSTRING(UC FROM 511	FOR 17)		AS  NUMERIC)	AS VALOR_CEDI_PUENT,	
CAST(SUBSTRING(UC FROM 528	FOR 17)		AS  NUMERIC)	AS PRIMA_CEDI_PUENT,	
CAST(SUBSTRING(UC FROM 545	FOR 17)		AS  NUMERIC)	AS VALOR_CEDI_FACOB,	
CAST(SUBSTRING(UC FROM 562	FOR 17)		AS  NUMERIC)	AS PRIMA_CEDI_FACOB,	
CAST(SUBSTRING(UC FROM 579	FOR 17)		AS  NUMERIC)	AS VALOR_FACULTATIV,	
CAST(SUBSTRING(UC FROM 596	FOR 17)		AS  NUMERIC)	AS PRIMA_FACULTATIV,	
CAST(SUBSTRING(UC FROM 613	FOR 2)		AS  TEXT)	AS T,	
CAST(SUBSTRING(UC FROM 615	FOR 10)		AS  NUMERIC)	AS PORC_IND_EDIF,
CAST(SUBSTRING(UC FROM 625	FOR 10)		AS  NUMERIC)	AS PORC_IND_MERC,	
CAST(SUBSTRING(UC FROM 635	FOR 10)		AS  NUMERIC)	AS PORC_IND_MAQ,
CAST(SUBSTRING(UC FROM 645	FOR 10)		AS  NUMERIC)	AS PORC_IND_MFIJ,	
CAST(SUBSTRING(UC FROM 655	FOR 10)		AS  NUMERIC)	AS PORC_IND_ART,	
CAST(SUBSTRING(UC FROM 665	FOR 11)		AS  TEXT)	AS CLASIF_RIE,	
CAST(SUBSTRING(UC FROM 676	FOR 6)		AS  TEXT)	AS MTERP,	
CAST(SUBSTRING(UC FROM 682	FOR 6)		AS  TEXT)	AS CONT	,
CAST(SUBSTRING(UC FROM 688	FOR 6)		AS  TEXT)	AS OPTIKA,	
CAST(SUBSTRING(UC FROM 698	FOR 10)		AS  TEXT)	AS ENT_OFIC,	
CAST(SUBSTRING(UC FROM 713	FOR 15)		AS  TEXT)	AS LOC_OFIC,
CAST(SUBSTRING(UC FROM 722	FOR 9)		AS  TEXT)	AS NOMBRE_INTERMEDIARIO,
CAST(SUBSTRING(UC FROM 752	FOR 30)		AS  TEXT)	AS T_GARANT,	
CAST(SUBSTRING(UC FROM 791	FOR 39)		AS  TEXT)	AS POLI_PRINCIPAL,	
CAST(SUBSTRING(UC FROM 805	FOR 16)		AS  BIGINT)	AS SEGMENTO
INTO ", P500,"
FROM P501B;

DROP TABLE IF EXISTS P501B;


WITH A AS(
    select*,
    case
    when segmento is not null then (segmento-(floor(segmento/1000)*1000)) end as SUBPRODUCTO
    from ", P500,")

SELECT A.*, DES_PARAMETROS.LINEA_CRED
INTO ",P500,"_1
FROM A INNER JOIN DES_PARAMETROS ON 
a.ram=des_parametros.producto and
A.SUBPRODUCTO=DES_PARAMETROS.SUBPRODUCTO;

DROP TABLE ", P500,";

SELECT*
    INTO ",P500,"
FROM ",P500,"_1;

DROP TABLE IF EXISTS ", P500,"_1;

insert into endosos_desempleo
select
  numero_poliza,
  endoso,
  tipo_end,
  nit_asegurado,
  fec_vig_pol,
  fecha_equipo,
  valor_asegurado,
  prima_seguro,
  linea_cred
from ",P500,"

      ",sep= ""))


#write.csv(A,"C:/Users/Public/Documents/B.csv")
