#source('C:/Users/1010208320/Documents/R/CONEXIONES/CONEXION LocalHost.r')



###################################
# PARAMETROS                      #
#                                 #
# TABLA QUE SE VA A LEER          #
#                                 #
#P500 <- "P500201701"             #
#P501 <- "P501201701"             #
#FECHA_EQUIPO_INF <- "01-01-2017" #
#FECHA_EQUIPO_SUP <- "01-02-2017" #
###################################

#--CALCULO DE:
#-- NUMERO DE NUEVOS NEGOCIOS
#-- VALOR DE PRIMAS NUEVOS NEGOCIOS


NN500<-dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = '  ' AND
(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)=1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >='",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED", sep=" "))

atrib <- rep("NN",nrow(NN500))
NN500<-cbind(atrib,NN500)

#-- RENOVACIONES , NUMERO Y VALOR

RENOV500 <- dbGetQuery(con, paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = '  ' AND
(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED", sep=" "))

atrib <- rep("RENOV",nrow(RENOV500))
RENOV500<-cbind(atrib,RENOV500)


#-- CANCELACIONES TOTAL

CANCEL_TOTAL500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED", sep=" "))

atrib <- rep("CANCEL_TOTAL",nrow(CANCEL_TOTAL500))
CANCEL_TOTAL500<-cbind(atrib,CANCEL_TOTAL500)


#-- CANCELACIONES NUEVOS, NUMERO Y VALOR

CANCEL_NN500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)=1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED",sep=" "))

atrib <- rep("CANCEL_NN",nrow(CANCEL_NN500))
CANCEL_NN500<-cbind(atrib,CANCEL_NN500)


#-- CANCELACIONES RENOVACIONES, NUMERO Y VALOR

CANCEL_RENOV500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED",sep=" "))

atrib <- rep("CANCEL_RENOV",nrow(CANCEL_RENOV500))
CANCEL_RENOV500<-cbind(atrib,CANCEL_RENOV500)


#-- DISMINUCION DE VAS
DISM_VAS500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AP'  AND
--(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED",sep=" "))

atrib <- rep("DISM_VAS",nrow(DISM_VAS500))
DISM_VAS500<-cbind(atrib,DISM_VAS500)


#-- MODIFICACION VAS

MODIF_VAS500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AD'  AND
--(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED",sep=" "))

atrib <- rep("MODIF_VAS",nrow(MODIF_VAS500))
MODIF_VAS500<-cbind(atrib,MODIF_VAS500)


#-- REHABILITACIONES

REAHBIL500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = 'RE'  AND
--(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED",sep=" "))

atrib <- rep("REAHBIL",nrow(REAHBIL500))
REAHBIL500<-cbind(atrib,REAHBIL500)


#-- MODIFICACIONES SM	

MODIF_SM500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
FROM", P500,"
WHERE 
SUBSTRING(TIPO_END FROM 7 FOR 2) = 'SM'  AND
--(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED",sep=" "))

atrib <- rep("MODIF_SM",nrow(MODIF_SM500))
MODIF_SM500<-cbind(atrib,MODIF_SM500)


#-- CESION

CESION500 <- dbGetQuery(con,paste(
"SELECT LINEA_CRED, COUNT(PRIMA_CEDI_CUOTA) AS N, SUM(PRIMA_CEDI_CUOTA) AS VALOR
FROM", P500,"
WHERE 
--SUBSTRING(TIPO_END FROM 7 FOR 2) = 'RE'  AND
--(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
(FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
GROUP BY LINEA_CRED",sep=" "))

atrib <- rep("CESION",nrow(CESION500))
CESION500<-cbind(atrib,CESION500)


SEGUIMINETO_P500<-rbind(NN500,RENOV500,CANCEL_NN500,CANCEL_RENOV500,CANCEL_TOTAL500,DISM_VAS500,MODIF_VAS500,REAHBIL500,MODIF_SM500,CESION500)
SEGUIMINETO_P500_1<-rbind(SEGUIMINETO_P500[,1:2])
N<-"N"
VALOR<-"VALOR"


SEGUIMINETO_P500_1<-merge(SEGUIMINETO_P500_1,y = N)
SEGUIMINETO_P500_2<-merge(SEGUIMINETO_P500[,1:2],y = VALOR)
SEGUIMINETO_P500_3<-rbind(SEGUIMINETO_P500_1,SEGUIMINETO_P500_2)

SEGUIMINETO_P500_1<-SEGUIMINETO_P500[,c(1,3)]
SEGUIMINETO_P500_2<-SEGUIMINETO_P500[,c(1,4)]
names(SEGUIMINETO_P500_2)<-c("atrib","n")

SEGUIMINETO_P500_1<-rbind(SEGUIMINETO_P500_1,SEGUIMINETO_P500_2)
SEGUIMINETO_P500_3<-cbind(SEGUIMINETO_P500_3,SEGUIMINETO_P500_1[,2])

names(SEGUIMINETO_P500_3)<-c("atrib","linea_cred","atrib2",FECHA_EQUIPO_INF)

# ##########################################################################
# # P501
# ##########################################################################
# 
# NN501<-dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = '  ' AND
#     (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)=1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >='",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED", sep=" "))
# 
# atrib <- rep("NN",nrow(NN501))
# NN501<-cbind(atrib,NN501)
# 
# #-- RENOVACIONES , NUMERO Y VALOR
# 
# RENOV501 <- dbGetQuery(con, paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = '  ' AND
#     (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED", sep=" "))
# 
# atrib <- rep("RENOV",nrow(RENOV501))
# RENOV501<-cbind(atrib,RENOV501)
# 
# 
# #-- CANCELACIONES TOTAL
# 
# CANCEL_TOTAL501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED", sep=" "))
# 
# atrib <- rep("CANCEL_TOTAL",nrow(CANCEL_TOTAL501))
# CANCEL_TOTAL501<-cbind(atrib,CANCEL_TOTAL501)
# 
# 
# #-- CANCELACIONES NUEVOS, NUMERO Y VALOR
# 
# CANCEL_NN501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
#     (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)=1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("CANCEL_NN",nrow(CANCEL_NN501))
# CANCEL_NN501<-cbind(atrib,CANCEL_NN501)
# 
# 
# #-- CANCELACIONES RENOVACIONES, NUMERO Y VALOR
# 
# CANCEL_RENOV501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
#     (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("CANCEL_RENOV",nrow(CANCEL_RENOV501))
# CANCEL_RENOV501<-cbind(atrib,CANCEL_RENOV501)
# 
# 
# #-- DISMINUCION DE VAS
# DISM_VAS501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AP'  AND
#     --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("DISM_VAS",nrow(DISM_VAS501))
# DISM_VAS501<-cbind(atrib,DISM_VAS501)
# 
# 
# #-- MODIFICACION VAS
# 
# MODIF_VAS501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AD'  AND
#     --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("MODIF_VAS",nrow(MODIF_VAS501))
# MODIF_VAS501<-cbind(atrib,MODIF_VAS501)
# 
# 
# #-- REHABILITACIONES
# 
# REAHBIL501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = 'RE'  AND
#     --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("REAHBIL",nrow(REAHBIL501))
# REAHBIL501<-cbind(atrib,REAHBIL501)
# 
# 
# #-- MODIFICACIONES SM	
# 
# MODIF_SM501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#     FROM", P501,"
#     WHERE 
#     SUBSTRING(TIPO_END FROM 7 FOR 2) = 'SM'  AND
#     --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("MODIF_SM",nrow(MODIF_SM501))
# MODIF_SM501<-cbind(atrib,MODIF_SM501)
# 
# 
# #-- CESION
# 
# CESION501 <- dbGetQuery(con,paste(
#     "SELECT LINEA_CRED, COUNT(PRIMA_CEDI_CUOTA) AS N, SUM(PRIMA_CEDI_CUOTA) AS VALOR
#     FROM", P501,"
#     WHERE 
#     --SUBSTRING(TIPO_END FROM 7 FOR 2) = 'RE'  AND
#     --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("CESION",nrow(CESION501))
# CESION501<-cbind(atrib,CESION501)
# 
# 
# SEGUIMINETO_P501<-rbind(NN501,RENOV501,CANCEL_NN501,CANCEL_RENOV501,CANCEL_TOTAL501,DISM_VAS501,MODIF_VAS501,REAHBIL501,MODIF_SM501,CESION501)
# SEGUIMINETO_P501_1<-rbind(SEGUIMINETO_P501[,1:2])
# N<-"N"
# VALOR<-"VALOR"
# 
# 
# SEGUIMINETO_P501_1<-merge(SEGUIMINETO_P501_1,y = N)
# SEGUIMINETO_P501_2<-merge(SEGUIMINETO_P501[,1:2],y = VALOR)
# SEGUIMINETO_P501_3<-rbind(SEGUIMINETO_P501_1,SEGUIMINETO_P501_2)
# 
# SEGUIMINETO_P501_1<-SEGUIMINETO_P501[,c(1,3)]
# SEGUIMINETO_P501_2<-SEGUIMINETO_P501[,c(1,4)]
# names(SEGUIMINETO_P501_2)<-c("atrib","n")
# 
# SEGUIMINETO_P501_1<-rbind(SEGUIMINETO_P501_1,SEGUIMINETO_P501_2)
# SEGUIMINETO_P501_3<-cbind(SEGUIMINETO_P501_3,SEGUIMINETO_P501_1[,2])
# 
# names(SEGUIMINETO_P501_3)<-c("atrib","linea_cred","atrib2",FECHA_EQUIPO_INF)


############################################################
#############################################################
###########################################################################

# ##########################################################################
# # P506
# ##########################################################################
# 
# NN506<-dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = '  ' AND
#   (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)=1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >='",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED", sep=" "))
# 
# atrib <- rep("NN",nrow(NN506))
# NN506<-cbind(atrib,NN506)
# 
# #-- RENOVACIONES , NUMERO Y VALOR
# 
# RENOV506 <- dbGetQuery(con, paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = '  ' AND
#   (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED", sep=" "))
# 
# atrib <- rep("RENOV",nrow(RENOV506))
# RENOV506<-cbind(atrib,RENOV506)
# 
# 
# #-- CANCELACIONES TOTAL
# 
# CANCEL_TOTAL506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED", sep=" "))
# 
# atrib <- rep("CANCEL_TOTAL",nrow(CANCEL_TOTAL506))
# CANCEL_TOTAL506<-cbind(atrib,CANCEL_TOTAL506)
# 
# 
# #-- CANCELACIONES NUEVOS, NUMERO Y VALOR
# 
# CANCEL_NN506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
#   (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)=1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("CANCEL_NN",nrow(CANCEL_NN506))
# CANCEL_NN506<-cbind(atrib,CANCEL_NN506)
# 
# 
# #-- CANCELACIONES RENOVACIONES, NUMERO Y VALOR
# 
# CANCEL_RENOV506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AT'  AND
#   (NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("CANCEL_RENOV",nrow(CANCEL_RENOV506))
# CANCEL_RENOV506<-cbind(atrib,CANCEL_RENOV506)
# 
# 
# #-- DISMINUCION DE VAS
# DISM_VAS506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AP'  AND
#   --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("DISM_VAS",nrow(DISM_VAS506))
# DISM_VAS506<-cbind(atrib,DISM_VAS506)
# 
# 
# #-- MODIFICACION VAS
# 
# MODIF_VAS506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = 'AD'  AND
#   --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("MODIF_VAS",nrow(MODIF_VAS506))
# MODIF_VAS506<-cbind(atrib,MODIF_VAS506)
# 
# 
# #-- REHABILITACIONES
# 
# REAHBIL506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = 'RE'  AND
#   --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("REAHBIL",nrow(REAHBIL506))
# REAHBIL506<-cbind(atrib,REAHBIL506)
# 
# 
# #-- MODIFICACIONES SM	
# 
# MODIF_SM506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_SEGURO) AS N, SUM(PRIMA_SEGURO) AS VALOR
#   FROM", P506,"
#   WHERE 
#   SUBSTRING(TIPO_END FROM 7 FOR 2) = 'SM'  AND
#   --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#   (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#   GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("MODIF_SM",nrow(MODIF_SM506))
# MODIF_SM506<-cbind(atrib,MODIF_SM506)
# 
# 
# #-- CESION
# 
# CESION506 <- dbGetQuery(con,paste(
#   "SELECT LINEA_CRED, COUNT(PRIMA_CEDI_CUOTA) AS N, SUM(PRIMA_CEDI_CUOTA) AS VALOR
#     FROM", P506,"
#     WHERE 
#     --SUBSTRING(TIPO_END FROM 7 FOR 2) = 'RE'  AND
#     --(NUMERO_POLIZA-FLOOR(NUMERO_POLIZA/100)*100)>1 AND
#     (FECHA_EQUIPO < '",FECHA_EQUIPO_SUP,"' AND FECHA_EQUIPO >= '",FECHA_EQUIPO_INF,"')
#     GROUP BY LINEA_CRED",sep=" "))
# 
# atrib <- rep("CESION",nrow(CESION506))
# CESION506<-cbind(atrib,CESION506)
# 
# 
# SEGUIMINETO_P506<-rbind(NN506,RENOV506,CANCEL_NN506,CANCEL_RENOV506,CANCEL_TOTAL506,DISM_VAS506,MODIF_VAS506,REAHBIL506,MODIF_SM506,CESION506)
# SEGUIMINETO_P506_1<-rbind(SEGUIMINETO_P506[,1:2])
# N<-"N"
# VALOR<-"VALOR"
# 
# 
# SEGUIMINETO_P506_1<-merge(SEGUIMINETO_P506_1,y = N)
# SEGUIMINETO_P506_2<-merge(SEGUIMINETO_P506[,1:2],y = VALOR)
# SEGUIMINETO_P506_3<-rbind(SEGUIMINETO_P506_1,SEGUIMINETO_P506_2)
# 
# SEGUIMINETO_P506_1<-SEGUIMINETO_P506[,c(1,3)]
# SEGUIMINETO_P506_2<-SEGUIMINETO_P506[,c(1,4)]
# names(SEGUIMINETO_P506_2)<-c("atrib","n")
# 
# SEGUIMINETO_P506_1<-rbind(SEGUIMINETO_P506_1,SEGUIMINETO_P506_2)
# SEGUIMINETO_P506_3<-cbind(SEGUIMINETO_P506_3,SEGUIMINETO_P506_1[,2])
# 
# names(SEGUIMINETO_P506_3)<-c("atrib","linea_cred","atrib2",FECHA_EQUIPO_INF)


############################################################
#############################################################
###########################################################################










SEGUIMINETO_TOTAL <- rbind(SEGUIMINETO_P500_3)##),SEGUIMINETO_P501_3,SEGUIMINETO_P506_3)

write.csv(SEGUIMINETO_TOTAL,paste('C:/Users/Public/Documents/DESEMPLEO/SEGUIMIENTO/VALIDACION/DESEMPLEO ',FECHA_EQUIPO_INF,".csv",sep = ''))
